# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname1
      properties:
        uref:
          type: "string"
        lname1:
          type: "string"
        lname2:
          type: "string"
        fname1:
          type: "string"
        fname2:
          type: "string"
        email1:
          type: "string"
          format: "email"
        email2:
          type: "string"
          format: "email"
        phone1:
          type: "string"
        phone2:
          type: "string"
        address1:
          type: "string"
        address2:
          type: "string"
        sex:
          type: "string"
  parameters:
    uref:
      name: "uref"
      description: "unique reference of the person to get"
      in: path
      required: True
      schema:
        type: "string"
    lname1:
      name: "lname1"
      description: "Last name 1 of the person to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
          description: "Person to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"
  /people/{uref}:
    get:
      operationId: "people.read_one_by_uref"
      tags:
        - People
      summary: "Read one person using unique reference"
      parameters:
        - $ref: "#/components/parameters/uref"
      responses:
        "200":
          description: "Successfully read ONE person"
  /people/by_l_name/{lname1}:
    get:
      operationId: "people.read_all_by_lname1"
      tags:
        - People
      summary: "Read all person having the last name given"
      parameters:
        - $ref: "#/components/parameters/lname1"
      responses:
        "200":
          description: "Successfully read ALL person by LNAME1"



